/* 藥動學 內容資料：講義、各頁重點（整合使用者課後重點整理）、題庫、臨床情境、名詞、概念地圖 */
window.COURSE = {
  id: "pk",
  title: "💊 藥物動力學在新藥開發中的應用（115-1）",
  intro: "1 學分、每次 2 小時，定位在臨床試驗應用。老師說：「你要告訴我它的<b>意義</b>，不要告訴我它的翻譯。」考試是 in-class，講義以外的口頭補充也會考，所以每頁都附上老師講這頁的原音。",
  tiles: [
    { href: "pre", icon: "🧭", title: "前測診斷", desc: "8 題找出 ADME 與參數哪裡最不穩" },
    { href: "lec/pk_L1/1", icon: "📖", title: "講義＋老師原音", desc: "每頁直接播老師講這頁的片段；頁旁附你課後整理的口頭補充" },
    { href: "case", icon: "🏥", title: "臨床情境題", desc: "治「參數背得出、床邊用不上」：剝半長效錠、PK 抽血、低白蛋白、codeine、TDM" },
    { href: "tool/sim", icon: "📈", title: "血中濃度模擬器", desc: "治「公式看不出畫面」：拉 Vd、CL、ka、給藥間隔，看曲線與 MEC/MTC" },
    { href: "quiz", icon: "🧪", title: "分層自我檢測", desc: "概念→計算→判讀，依單元篩選" },
    { href: "wrong", icon: "📕", title: "錯題本", desc: "錯題連回講義頁與錄音時間點，連對兩次才移出" },
    { href: "map", icon: "🗺️", title: "概念地圖", desc: "治「ADME 跟參數各自為政」：點方塊看意義與關係" },
    { href: "gl", icon: "🔤", title: "名詞中英對照", desc: "老師要意義不要翻譯：先說出意義再翻卡" },
  ],
  lectures: [
    { id: "pk_L1", icon: "🧬", title: "1. Introduction of PK（ADME）", short: "PK導論", date: "2026-09-11", pages: 15, ar: "727/1048", audio: true,
      keys: {
        1: "<b>Cmax／Tmax／AUC</b>＝藥物的「履歷表」。吸收程度相同（AUC 相同）時，吸收越快 → Cmax 越高、Tmax 越早。<br>治療區間：MEC～MTC；區間窄的藥要做 <b>TDM</b>（vancomycin、aminoglycosides、phenytoin）。<br>此曲線型態適用口服或 IM；SC 會經淋巴系統，上升更慢、Tmax 更晚。IV bolus 沒有吸收相，F＝100%。",
        2: "ADME 的 <b>E＝Excretion（排泄）</b>，不是 elimination；Elimination＝Metabolism＋Excretion。<br>血中濃度會變化，是 ADME 四個過程造成的。",
        3: "三類<b>不可磨粉／剝半</b>：長效劑型（extended release）、腸溶或保護膜衣、舌下／口頰吸收。<br>老師親歷案例：長效錠剝半給小孩 → 整日劑量瞬間釋出 → 超過 MTC。<br>只有 <b>free drug</b> 能過 BBB、被代謝、被腎絲球過濾、產生藥效與副作用。fu＝游離分率；fe＝以原型從尿排出的比例（F＝fraction）。",
        4: "口服必經：<b>崩散 → 溶離 → 小腸吸收 → 腸壁代謝 → 肝門靜脈 → 肝代謝 → 全身循環</b>。藥物不溶解就不會吸收。<br>高油脂餐讓胃排空變慢 → 吸收延遲；「飯後給藥」要定義吃了什麼。腹瀉 → 停留時間不足 → 吸收不良。",
        5: "小腸也是代謝器官：<b>CYP3A4</b>。葡萄柚汁抑制小腸 CYP3A4 → 首渡代謝減少 → AUC 暴增（cisapride → QT 延長致死）。<br>腸肝循環：經膽汁排入腸道再吸收，曲線可能出現雙峰（但雙峰不一定是腸肝循環）。",
        6: "跨膜運輸：被動擴散、細胞旁、促進性與主動運輸（transporter）、胞吞。Transporter 會<b>飽和</b>與<b>競爭</b>：levodopa 與高蛋白飲食搶同一個胺基酸轉運蛋白。<br><b>Vd＝A／C</b>：分布廣度的指標，不是真實體積；多數情況不隨濃度改變。",
        7: "分布三因素：灌流、擴散、蛋白與組織結合。主要結合蛋白：<b>albumin</b>、α1-acid glycoprotein、lipoproteins。<br>結合率 ≥95% 是高度蛋白結合藥物。低白蛋白（腎病、肝病、燒燙傷、懷孕）或競爭結合會讓 fu 上升。",
        8: "<b>F＝Fgl×Fgw×Fh</b>。例：100 個分子 → 小腸吸收後被腸壁代謝 → 肝再代謝 → 剩 30 個進全身循環，F＝30%。<br>F 低 → 個體差異大 → Phase 3 需要更多受試者。<br>Phase I（敲打、官能基化）vs Phase II（接合）——與臨床試驗分期無關。Prodrug：clopidogrel 需代謝才有活性。",
        9: "CYP 占比：3A ＞ 2D6 ＞ 2C ＞ 1A2 ＞ 2E1。<br>代謝表型：<b>PM</b>（活性低）、<b>EM</b>（正常）、<b>UM</b>（基因重複、代謝過快）。Codeine 經 CYP2D6 變成 morphine，UM 兒童術後呼吸抑制甚至死亡。",
        10: "<b>CL＝Q×ER</b>，ER＝(Ca−Cv)/Ca＝fu·CLint／(Q＋fu·CLint)。fu 出現在公式裡 → 只有 free drug 能被清除。",
        11: "GFR 與游離藥物濃度直接相關；<b>GFR＜80 mL/min</b> 通常就要考慮腎功能不全對排泄的影響。",
        12: "非線性（劑量依賴）PK：酵素飽和時，劑量加倍 AUC 不只加倍。影響是否可豁免較高含量的 BE 試驗、緩釋劑型該做哪些試驗。",
        13: "低劑量（C≪Km）：一階動力學，t½＝0.693/k 固定。高劑量：酵素飽和 → 先以零階（固定量）排除，濃度下降後才轉為一階。",
        14: "種族因素：<b>內在</b>（基因、年齡、肝腎功能、體重、受體敏感性）vs <b>外在</b>（環境、飲食、吸菸飲酒、醫療常規、法規）。",
        15: "老年人：胃酸↓、體水分↓、體脂↑（極性藥 Vd↓、脂溶性藥 Vd↑）、白蛋白↓（酸性高結合藥 fu↑）、肝血流↓、GFR↓（腎排藥 t½↑）。<br>Bridging study 八項考量：非線性 PK、PD 曲線陡、治療區間窄、單一代謝途徑、多型性酵素、對種族敏感、F 個體差異大、F 低易受飲食影響。",
      } },
    { id: "pk_L2", icon: "📐", title: "2. Basic concepts in PK parameters", short: "PK參數", date: "2026-09-18", pages: 10, ar: "3/4", audio: true,
      keys: {
        2: "一室開放模型三假設：瞬間分布、一階排除、全身視為單一室。<br>C＝C₀·e<sup>−kt</sup>；半對數圖呈直線、斜率＝−k。<b>AUC＝C₀/k＝D/CL</b>。",
        3: "<b>t½＝0.693/k</b>；k＝ke＋km＋k<sub>others</sub>。半衰期也能用尿液排泄速率推估。<br>定速輸注：<b>Css＝R₀/CL</b>——穩定態濃度只由輸注速率與清除率決定，與 Vd 無關；到達速度由 t½ 決定。",
        4: "1 個 t½ 到 50%、2 個 75%、3 個 88%、<b>3.32 個 90%</b>、4 個 94%、5 個 97%。實務以 4–5 個 t½ 視為穩定態。",
        5: "<b>Loading dose＝Vd×(Cp,desired−Cp,initial)／(S×F)</b>。負荷劑量看 Vd，維持速率看 CL；目的是不用等 4–5 個半衰期。",
        6: "Bioavailability＝原型藥到達全身循環的<b>速率（Cmax、Tmax）</b>與<b>程度（AUC）</b>。<br>tmax＝ln(ka/k)／(ka−k)，與劑量無關。CL＝S·F·D／AUC。",
        7: "絕對 F：和 IV 比（F<sub>IV</sub>＝100%）。相對 F：兩個血管外劑型互比（學名藥 vs 原廠，BE 試驗）。圖中的 lag time＝給藥後濃度還沒開始上升的延遲。",
        8: "<b>Flip-flop</b>：ka＜k 時（常見於緩釋劑型），曲線末端斜率反映的是吸收而非排除，誤判會算錯半衰期。<br>疊加原理前提：一階排除、前面劑量不改變後面劑量的 PK（無酵素誘導/抑制、無轉運飽和、無病理變化）。",
        9: "蓄積因子 <b>R＝1／(1−e<sup>−kτ</sup>)</b>；τ 相對 t½ 越短，蓄積越多（τ＝t½ 時 R＝2）。<br>二室模型：中央室（血漿與灌流好的組織）↔ 組織室，k12、k21、k10。",
        10: "Cp＝A·e<sup>−αt</sup>＋B·e<sup>−βt</sup>：α 相（分布，快）＋β 相（排除，慢）。半對數圖呈兩段斜率 → 判斷二室模型。",
      } },
  ],
  pre: {
    intro: "8 題、約 5 分鐘，找出 ADME 與參數哪一塊最需要補。",
    ids: ["p01", "p05", "p08", "p12", "p16", "p19", "p22", "p25"],
  },
  caseIntro: "情境都來自腫瘤病房與臨床試驗現場——老師說過，臨床試驗裡只有護理師能抽血。先想「這跟哪個 PK 參數有關」，再作答。",
  questions: [
    // ── 導論：概念 ──
    { id: "p01", lec: "pk_L1", lv: "概念", q: "老師特別澄清 ADME 的「E」指的是什麼？",
      opts: ["Elimination（排除）", "Excretion（排泄）", "Effect（藥效）", "Enzyme（酵素）"], a: 1,
      ex: "E＝Excretion。Elimination＝Metabolism＋Excretion，已經包含代謝，所以說 ADME 的 E 是 elimination 不精確。", ref: ["pk_L1", 2] },
    { id: "p02", lec: "pk_L1", lv: "概念", q: "下列哪一種藥物<b>可以</b>剝半或磨粉？",
      opts: ["長效緩釋錠（extended release）", "腸溶錠（enteric coated）", "舌下錠", "講義沒有列出限制的一般速放錠"], a: 3,
      ex: "講義第 3 頁三類不可破壞：長效、腸溶/保護膜衣、舌下/口頰吸收。一般速放錠仍要查仿單與藥劑部資料，但不在這三類。", ref: ["pk_L1", 3] },
    { id: "p03", lec: "pk_L1", lv: "概念", q: "哪一種型態的藥物能通過 BBB、被代謝、並產生副作用？",
      opts: ["與白蛋白結合的藥物", "游離（free, unbound）藥物", "所有藥物都可以", "只有代謝物"], a: 1,
      ex: "只有 free drug 能跨過屏障、進肝細胞、被腎絲球過濾、作用在受體上。臨床試驗一般測總濃度，但概念要有。", ref: ["pk_L1", 3] },
    { id: "p04", lec: "pk_L1", lv: "概念", q: "「皮下注射（SC）」的血中濃度曲線與口服、IM 相比，通常有什麼特徵？",
      opts: ["Tmax 更早", "沒有吸收相", "要經淋巴系統，上升更慢、Tmax 更晚", "F 一定是 100%"], a: 2,
      ex: "SC 藥物（常見於大分子抗體藥）需經淋巴系統才進血液，曲線較平緩。", ref: ["pk_L1", 1] },
    { id: "p05", lec: "pk_L1", lv: "概念", q: "關於 Vd（表觀分布體積），下列何者正確？",
      opts: ["就是病人真實的體液量", "Vd 越大代表藥物分布越廣，半衰期通常越長", "Vd 會隨濃度大幅改變", "只有口服藥才有 Vd"], a: 1,
      ex: "Vd＝A/C 是分布廣度的指標，很少對應真實體積（可以大到每公斤數公升），多數情況不隨濃度改變。", ref: ["pk_L1", 6] },
    { id: "p06", lec: "pk_L1", lv: "概念", q: "Clopidogrel（保栓通）需要經過代謝才有抗血小板作用，這種藥稱為？",
      opts: ["Prodrug（前驅藥）", "Active metabolite 的相反", "Phase II 藥物", "Enteric-coated drug"], a: 0,
      ex: "Parent drug 本身不是主要活性形式，要經 CYP 代謝成活性代謝物。CYP2C19 PM 者療效可能不佳。", ref: ["pk_L1", 8] },
    { id: "p07", lec: "pk_L1", lv: "概念", q: "這門課說的「Phase I／Phase II 代謝」和臨床試驗的 Phase I／II 有什麼關係？",
      opts: ["完全相同", "Phase I 代謝都在 Phase I 試驗研究", "完全無關，只是名稱相同", "Phase II 代謝只發生在病人身上"], a: 2,
      ex: "Phase I 代謝＝官能基化（「敲打」），Phase II＝接合反應；和試驗分期無關，老師特別澄清。", ref: ["pk_L1", 8] },
    // ── 導論：判讀 ──
    { id: "p08", lec: "pk_L1", lv: "判讀", q: "兩個劑型的 AUC 相同，但 A 劑型吸收比較快。和 B 相比，A 最可能？",
      opts: ["Cmax 較高、Tmax 較早", "Cmax 較低、Tmax 較晚", "AUC 較大", "半衰期一定較短"], a: 0,
      ex: "吸收程度一樣（AUC 相同），吸收越快，峰值越高、到峰越早。", ref: ["pk_L1", 1] },
    { id: "p09", lec: "pk_L1", lv: "判讀", q: "某藥白蛋白結合率從 99% 降到 98%，另一藥從 90% 降到 85%。哪一個藥的游離藥物<b>相對</b>增加比較多？",
      opts: ["第一個藥（1%→2%，變 2 倍）", "第二個藥（10%→15%，變 1.5 倍）", "兩者一樣", "無法比較"], a: 0,
      ex: "結合率只掉 1 個百分點，但 free fraction 翻倍；決定藥效與副作用的是 free drug 的相對倍數。高度結合（≥95%）的藥要特別小心。", ref: ["pk_L1", 7] },
    { id: "p10", lec: "pk_L1", lv: "判讀", q: "病人喝了大量葡萄柚汁後，一個經 CYP3A4 代謝的口服藥 AUC 大增。主要機轉是？",
      opts: ["腎排泄增加", "小腸 CYP3A4 被抑制，首渡代謝減少", "蛋白結合增加", "胃排空加快"], a: 1,
      ex: "葡萄柚汁主要抑制腸壁 CYP3A4 → Fgw 上升 → F 與 AUC 上升；cisapride 因此出現 QT 延長致死案例。", ref: ["pk_L1", 5] },
    { id: "p11", lec: "pk_L1", lv: "判讀", q: "CYP2D6 超快速代謝者（UM）使用 codeine，最擔心發生什麼？",
      opts: ["止痛完全無效", "Morphine 生成過快，呼吸抑制", "腎衰竭", "過敏反應"], a: 1,
      ex: "Codeine 要經 CYP2D6 轉成 morphine 才止痛。UM 轉得太快 → 呼吸抑制；PM 則可能止痛效果不佳。", ref: ["pk_L1", 9] },
    { id: "p12", lec: "pk_L1", lv: "判讀", q: "老年人體脂比例上升、體水分下降。脂溶性藥物的 Vd 與半衰期最可能？",
      opts: ["Vd↓、半衰期↓", "Vd↑、半衰期可能延長", "兩者不變", "Vd↓、半衰期↑"], a: 1,
      ex: "講義第 15 頁：極性藥 Vd↓、脂溶性藥 Vd↑；Vd 大 → 半衰期通常較長。", ref: ["pk_L1", 15] },
    { id: "p13", lec: "pk_L1", lv: "判讀", q: "某藥劑量從 100 mg 加到 200 mg，AUC 卻變成原來的 3 倍。最可能的解釋是？",
      opts: ["線性 PK", "非線性 PK：代謝酵素飽和", "抽血時間記錯", "Vd 變小"], a: 1,
      ex: "劑量與 AUC 不成比例（dose-disproportionality）→ 非線性、劑量依賴 PK；高濃度時酵素飽和，排除變慢。", ref: ["pk_L1", 12] },
    { id: "p14", lec: "pk_L1", lv: "概念", q: "Levodopa 和高蛋白飲食一起吃，療效變差。和哪一個概念最相關？",
      opts: ["被動擴散", "Transporter 的競爭與飽和", "腸肝循環", "Flip-flop"], a: 1,
      ex: "Levodopa 在小腸吸收與通過 BBB 都靠胺基酸轉運蛋白，飲食中的胺基酸會搶同一個 transporter。", ref: ["pk_L1", 6] },
    // ── 導論：計算 ──
    { id: "p15", lec: "pk_L1", lv: "計算", q: "某口服藥 Fgl＝0.8、Fgw＝0.75、Fh＝0.5，生體可用率 F 是多少？",
      opts: ["0.30", "0.50", "0.68", "2.05"], a: 0,
      ex: "F＝0.8×0.75×0.5＝0.30。", ref: ["pk_L1", 8] },
    { id: "p16", lec: "pk_L1", lv: "計算", q: "肝血流 Q＝90 L/h，某藥肝萃取比 ER＝0.5。肝清除率是多少？",
      opts: ["0.5 L/h", "45 L/h", "90 L/h", "180 L/h"], a: 1,
      ex: "CL＝Q×ER＝90×0.5＝45 L/h。", ref: ["pk_L1", 10] },
    { id: "p17", lec: "pk_L1", lv: "計算", q: "體內藥量 500 mg 時，血漿濃度 10 mg/L。Vd 是多少？",
      opts: ["5 L", "50 L", "500 L", "5000 L"], a: 1,
      ex: "Vd＝A/C＝500/10＝50 L。", ref: ["pk_L1", 6] },
    // ── 參數：概念 ──
    { id: "p18", lec: "pk_L2", lv: "概念", q: "定速輸注時，穩定態濃度 Css 由哪兩個因素決定？",
      opts: ["輸注速率與 Vd", "輸注速率與 CL", "Vd 與半衰期", "劑量與 F"], a: 1,
      ex: "Css＝R₀/CL，與 Vd 無關；Vd 與 CL 共同決定半衰期，也就是「多快」到穩定態。", ref: ["pk_L2", 3] },
    { id: "p19", lec: "pk_L2", lv: "概念", q: "給負荷劑量（loading dose）的目的，以及決定其大小的參數是？",
      opts: ["延長半衰期；CL", "快速到達目標濃度；Vd", "降低 Cmax；ka", "增加 F；Fh"], a: 1,
      ex: "LD＝Vd×Cp,desired／(S×F)。維持劑量或輸注速率才看 CL。", ref: ["pk_L2", 5] },
    { id: "p20", lec: "pk_L2", lv: "概念", q: "比較學名藥與原廠錠劑的吸收（BE 試驗），應該算哪一種生體可用率？",
      opts: ["絕對生體可用率（和 IV 比）", "相對生體可用率（兩個血管外劑型互比）", "萃取比", "蓄積因子"], a: 1,
      ex: "兩個口服劑型互比不需要 IV 資料，屬於相對生體可用率。", ref: ["pk_L2", 7] },
    { id: "p21", lec: "pk_L2", lv: "概念", q: "下列哪種情況會讓「疊加原理」不成立，無法用單劑資料預測多劑？",
      opts: ["一階排除", "藥物會誘導自己的代謝酵素", "每次劑量相同", "給藥間隔固定"], a: 1,
      ex: "前提：一階排除，且前面劑量不改變後面劑量的 PK（無酵素誘導／抑制、無轉運飽和、無病理生理變化）。", ref: ["pk_L2", 8] },
    // ── 參數：計算 ──
    { id: "p22", lec: "pk_L2", lv: "計算", q: "某藥排除速率常數 k＝0.1 h⁻¹，半衰期約是？",
      opts: ["0.69 h", "6.9 h", "10 h", "69 h"], a: 1,
      ex: "t½＝0.693/k＝6.93 h。", ref: ["pk_L2", 3] },
    { id: "p23", lec: "pk_L2", lv: "計算", q: "以 50 mg/h 定速輸注，CL＝5 L/h。穩定態濃度是？",
      opts: ["2.5 mg/L", "10 mg/L", "50 mg/L", "250 mg/L"], a: 1,
      ex: "Css＝R₀/CL＝50/5＝10 mg/L。", ref: ["pk_L2", 3] },
    { id: "p24", lec: "pk_L2", lv: "計算", q: "承上，該藥 t½＝6 h。開始輸注後大約多久可達 Css 的 90%？",
      opts: ["6 h", "約 20 h", "約 48 h", "要看 Vd"], a: 1,
      ex: "90% 需 3.32 個 t½＝3.32×6≈20 h。", ref: ["pk_L2", 4] },
    { id: "p25", lec: "pk_L2", lv: "計算", q: "Vd＝50 L，目標濃度 10 mg/L，病人體內原本沒有藥，IV 給藥（S＝F＝1）。負荷劑量是？",
      opts: ["5 mg", "50 mg", "500 mg", "5000 mg"], a: 2,
      ex: "LD＝50×(10−0)／1＝500 mg。", ref: ["pk_L2", 5] },
    { id: "p26", lec: "pk_L2", lv: "計算", q: "IV 100 mg 的 AUC＝50；口服 200 mg 的 AUC＝30（mg·h/L）。口服絕對生體可用率是？",
      opts: ["0.3", "0.6", "1.2", "0.15"], a: 0,
      ex: "F＝(AUC<sub>po</sub>/AUC<sub>iv</sub>)×(Dose<sub>iv</sub>/Dose<sub>po</sub>)＝(30/50)×(100/200)＝0.3。", ref: ["pk_L2", 7] },
    { id: "p27", lec: "pk_L2", lv: "計算", q: "口服 500 mg，F＝0.5，CL＝10 L/h（S＝1）。AUC 是多少？",
      opts: ["5 mg·h/L", "25 mg·h/L", "50 mg·h/L", "100 mg·h/L"], a: 1,
      ex: "AUC＝S·F·D／CL＝0.5×500／10＝25。", ref: ["pk_L2", 6] },
    { id: "p28", lec: "pk_L2", lv: "計算", q: "給藥間隔 τ 剛好等於 1 個半衰期，蓄積因子 R 是多少？",
      opts: ["1", "1.5", "2", "4"], a: 2,
      ex: "e<sup>−kτ</sup>＝0.5，R＝1/(1−0.5)＝2：穩定態時的濃度是單劑的 2 倍。", ref: ["pk_L2", 9] },
    // ── 參數：判讀 ──
    { id: "p29", lec: "pk_L2", lv: "判讀", q: "IV 給藥後，濃度在半對數圖上呈現「前段陡降、後段緩降」兩段斜率。最合理的判讀是？",
      opts: ["一室模型", "二室模型：α 分布相＋β 排除相", "非線性 PK", "吸收不完全"], a: 1,
      ex: "Cp＝A·e<sup>−αt</sup>＋B·e<sup>−βt</sup>；一室模型會是一條直線。", ref: ["pk_L2", 10] },
    { id: "p30", lec: "pk_L2", lv: "判讀", q: "某緩釋劑型吸收很慢（ka＜k）。直接用曲線末端斜率算出的「半衰期」其實反映的是？",
      opts: ["真正的排除半衰期", "吸收速率（flip-flop）", "分布相", "腎功能"], a: 1,
      ex: "Flip-flop：吸收成為速率限制步驟，末端斜率反映 ka，誤判會得到錯誤的排除半衰期。", ref: ["pk_L2", 8] },
    { id: "p31", lec: "pk_L2", lv: "判讀", q: "口服藥劑量加倍（線性 PK），下列何者正確？",
      opts: ["Cmax 加倍、tmax 不變", "Cmax 不變、tmax 加倍", "兩者都加倍", "t½ 加倍"], a: 0,
      ex: "tmax＝ln(ka/k)/(ka−k)，只和 ka、k 有關，與劑量無關。", ref: ["pk_L2", 6] },
    { id: "p32", lec: "pk_L2", lv: "判讀", q: "腎功能下降使某腎排藥的 CL 減半（Vd 不變），若給藥方式不變，會發生什麼？",
      opts: ["t½ 減半、Css 減半", "t½ 加倍、Css 加倍", "t½ 不變、Css 加倍", "兩者都不變"], a: 1,
      ex: "k＝CL/Vd 減半 → t½ 加倍；Css＝R₀/CL → 加倍。到達新穩定態也要更久。可到模擬器按「腎功能下降」看看。", ref: ["pk_L2", 3] },
  ],
  cases: [
    { id: "cp1", icon: "💊", title: "吞不下的長效嗎啡錠",
      story: "頭頸癌病人放置鼻胃管，醫囑「長效嗎啡錠 q12h」。家屬問你：「可以磨粉從鼻胃管灌嗎？還是剝一半比較好吞？」",
      qs: [
        { id: "cp1a", lec: "pk_L1", lv: "判讀", q: "把長效錠磨粉，最主要的 PK 風險是？", opts: ["F 下降、沒效", "緩釋結構被破壞，劑量瞬間釋出，Cmax 衝過 MTC", "Vd 變大", "半衰期變長"], a: 1,
          ex: "老師親歷案例：長效錠剝半 → 整日劑量瞬間釋出。對鴉片類藥物來說，就是呼吸抑制風險。", ref: ["pk_L1", 3] },
        { id: "cp1b", lec: "pk_L1", lv: "判讀", q: "比較合適的處理是？", opts: ["直接剝半，劑量不變", "磨粉後分兩次灌", "告知醫師與藥師，評估改用可經管路給藥的劑型或途徑", "改成一天一次整顆灌"], a: 2,
          ex: "長效、腸溶、舌下三類不可破壞；應回報處方者，改用適合管灌的劑型或其他途徑。", ref: ["pk_L1", 3] },
      ],
      debrief: "打開模擬器：口服、ka＝0.15（緩釋）與 ka＝3（被磨粉）各跑一次並「保留曲線比較」，看 Cmax 差多少、是否越過 MTC。" },
    { id: "cp2", icon: "🧪", title: "臨床試驗 PK 抽血晚了 6 分鐘",
      story: "你是研究護理師。Protocol 規定給藥後 <b>30 分鐘</b>抽 PK 血，但受試者緊張、血管收縮，你在 <b>36 分鐘</b>才抽到，而且那管血有點溶血。",
      qs: [
        { id: "cp2a", lec: "pk_L1", lv: "判讀", q: "採檢紀錄應該怎麼寫？", opts: ["照預定時間寫 30 分鐘，避免 deviation", "寫實際抽血時間 36 分鐘", "不寫時間", "重抽一次再寫 30 分鐘"], a: 1,
          ex: "分析時可以用實際時間校正；記錯時間，算出來的 PK 參數全部失去意義。吸收相濃度上升很快，幾分鐘差很多。", ref: ["pk_L1", 1] },
        { id: "cp2b", lec: "pk_L1", lv: "概念", q: "溶血為什麼要特別註記？", opts: ["溶血會改變藥效", "上清液變紅會干擾濃度分析", "溶血代表抽錯血管", "只是外觀問題"], a: 1,
          ex: "溶血造成分析干擾。另外，有些藥在血中會繼續被酵素代謝，採血管需加代謝抑制劑——務必細讀 protocol。", ref: ["pk_L1", 1] },
      ],
      debrief: "老師：「你抽血有問題、分析有問題，後面再怎麼解釋藥動意義都是錯的。」回想你的單位：給藥時間與抽血時間是怎麼記錄的？是否有「照醫囑時間補登」的習慣？" },
    { id: "cp3", icon: "🥣", title: "惡病質病人的「正常」藥物濃度",
      story: "一位胃癌惡病質病人，白蛋白 2.1 g/dL（明顯偏低），長期使用一種<b>高度蛋白結合</b>的抗癲癇藥。今天的藥物濃度報告（總濃度）在治療範圍內，但病人出現步態不穩、眼球震顫。",
      qs: [
        { id: "cp3a", lec: "pk_L1", lv: "判讀", q: "最可能的解釋是？", opts: ["檢驗錯誤", "總濃度正常，但白蛋白低讓游離藥物比例上升，實際作用濃度偏高", "藥物沒吸收", "Vd 變小造成濃度下降"], a: 1,
          ex: "副作用取決於 free drug；一般報告是總濃度。低白蛋白（腎病、肝病、燒燙傷、惡病質）會讓 fu 上升。", ref: ["pk_L1", 7] },
        { id: "cp3b", lec: "pk_L1", lv: "計算", q: "若結合率從 90% 掉到 80%，游離藥物濃度（總濃度不變時）變成原來的幾倍？", opts: ["1.1 倍", "1.5 倍", "2 倍", "10 倍"], a: 2,
          ex: "free：10% → 20%，是 2 倍。", ref: ["pk_L1", 7] },
      ],
      debrief: "你照顧的病人中，誰同時有低白蛋白和高度蛋白結合藥物？看到「濃度正常但症狀不對」時，可以主動和醫師、藥師討論游離濃度。" },
    { id: "cp4", icon: "🧬", title: "Codeine 止痛：有人沒效、有人太猛",
      story: "兩位癌症病人都用了相同劑量的 codeine。A 病人說完全不痛了但一直昏睡、呼吸變淺；B 病人說「吃了跟沒吃一樣」。",
      qs: [
        { id: "cp4a", lec: "pk_L1", lv: "判讀", q: "兩人最可能的 CYP2D6 表型分別是？", opts: ["A＝PM、B＝UM", "A＝UM、B＝PM", "兩人都是 EM", "和 CYP 無關"], a: 1,
          ex: "Codeine 是 prodrug，要經 CYP2D6 轉成 morphine。UM 轉太快 → 過量；PM 轉不出來 → 無效。", ref: ["pk_L1", 9] },
        { id: "cp4b", lec: "pk_L1", lv: "概念", q: "這個例子同時說明了哪兩個講義概念？", opts: ["Vd 與 CL", "Active metabolite／prodrug 與代謝多型性", "腸肝循環與 flip-flop", "GFR 與 ER"], a: 1,
          ex: "講義第 8 頁（活性代謝物）＋第 9 頁（EM／PM／UM）。", ref: ["pk_L1", 8] },
      ],
      debrief: "「同劑量、不同反應」時，除了疼痛評估，也把代謝差異放進你的假設清單。" },
    { id: "cp5", icon: "⏱️", title: "TDM 什麼時候抽 trough？",
      story: "某抗生素 <b>t½＝8 小時</b>，醫囑 <b>q12h</b> 靜脈給藥，需要監測谷底濃度（trough）。實習護生問：「第一劑給完就可以抽了嗎？」",
      qs: [
        { id: "cp5a", lec: "pk_L2", lv: "計算", q: "大約多久後可視為達到穩定態？", opts: ["8 小時", "12 小時", "32–40 小時", "一週"], a: 2,
          ex: "4–5 個半衰期：4×8＝32、5×8＝40 小時。", ref: ["pk_L2", 4] },
        { id: "cp5b", lec: "pk_L2", lv: "判讀", q: "比較合理的 trough 抽血時機是？", opts: ["第一劑給藥後馬上", "第二劑給藥前", "約第四劑給藥前（36 小時，已接近穩定態）", "隨時都可以"], a: 2,
          ex: "q12h：第四劑在 36 小時，已經超過 4 個半衰期（94%）。太早抽會低估穩定態濃度。實際時機依院內 TDM 規範。", ref: ["pk_L2", 4] },
        { id: "cp5c", lec: "pk_L2", lv: "判讀", q: "若病人急需達到治療濃度，醫師可能會怎麼做？", opts: ["縮短半衰期", "先給負荷劑量", "改口服", "降低劑量"], a: 1,
          ex: "負荷劑量讓濃度一開始就接近目標，不用等 4–5 個半衰期。", ref: ["pk_L2", 5] },
      ],
      debrief: "到模擬器設 IV bolus、τ＝12、t½≈8（例如 Vd＝40、CL＝3.5），觀察第幾劑之後谷底不再明顯上升；再打開負荷劑量比較。" },
  ],
  glossary: [
    { en: "Pharmacokinetics (PK)", zh: "藥物動力學", def: "描述藥物在體內 ADME 的時間歷程，以及它與療效、毒性強度的關係。", ref: ["pk_L1", 1] },
    { en: "Clinical pharmacokinetics", zh: "臨床藥物動力學", def: "把 PK 用在個別病人的安全有效治療。", ref: ["pk_L1", 1] },
    { en: "Biopharmaceutics", zh: "生物藥劑學", def: "劑型、給藥途徑如何影響藥物釋放、溶離與全身吸收。", ref: ["pk_L1", 2] },
    { en: "ADME", zh: "吸收、分布、代謝、排泄", def: "血中濃度之所以變化的四個過程；E＝Excretion。", ref: ["pk_L1", 2] },
    { en: "Elimination", zh: "排除", def: "代謝＋排泄，藥物從體內消失的總和。", ref: ["pk_L1", 2] },
    { en: "Cmax / Tmax", zh: "最高濃度／到達最高濃度時間", def: "反映吸收的「速率」；吸收越快，Cmax 越高、Tmax 越早。", ref: ["pk_L1", 1] },
    { en: "AUC", zh: "濃度-時間曲線下面積", def: "反映藥物暴露的「程度」；AUC＝F·D/CL。", ref: ["pk_L1", 1] },
    { en: "MEC / MTC", zh: "最低有效濃度／最低中毒濃度", def: "兩者之間是治療區間；區間窄的藥需要 TDM。", ref: ["pk_L1", 1] },
    { en: "TDM", zh: "治療藥物監測", def: "測量血中濃度調整劑量，用於治療區間窄的藥（vancomycin、aminoglycosides、phenytoin）。", ref: ["pk_L1", 1] },
    { en: "Disintegration / Dissolution", zh: "崩散／溶離", def: "大石頭變小石頭／小石頭溶成分子。不溶離就不會吸收。", ref: ["pk_L1", 3] },
    { en: "Extended release", zh: "長效（緩釋）劑型", def: "設計成慢慢釋放；剝半或磨粉會讓劑量瞬間釋出。", ref: ["pk_L1", 3] },
    { en: "Enteric coated", zh: "腸溶膜衣", def: "避免在胃中溶解；胃酸 pH 改變（老年人）也會影響。", ref: ["pk_L1", 3] },
    { en: "BBB", zh: "血腦屏障", def: "腦內緊密的微血管系統；與蛋白結合的藥物過不去。", ref: ["pk_L1", 3] },
    { en: "fu (fraction unbound)", zh: "游離分率", def: "血漿中未與蛋白結合的比例；只有游離藥物能作用、被代謝與排除。", ref: ["pk_L1", 3] },
    { en: "fe (fraction excreted)", zh: "原型尿中排泄分率", def: "以原型從尿液排出的比例；fe 高的藥受腎功能影響大。", ref: ["pk_L1", 3] },
    { en: "Gastric emptying", zh: "胃排空", def: "越慢 → 到小腸越晚 → 吸收延遲；高油脂餐會延緩。", ref: ["pk_L1", 5] },
    { en: "First-pass effect", zh: "首渡效應", def: "口服藥進入全身循環前，先在腸壁與肝臟被代謝掉一部分（諾曼第登陸比喻）。", ref: ["pk_L1", 4] },
    { en: "Enterohepatic recirculation", zh: "腸肝循環", def: "經膽汁排入腸道後再吸收，曲線可能出現第二個峰。", ref: ["pk_L1", 5] },
    { en: "Bioavailability (F)", zh: "生體可用率", def: "原型藥到達全身循環的速率與程度；F＝Fgl·Fgw·Fh。", ref: ["pk_L1", 8] },
    { en: "Transporter", zh: "轉運蛋白", def: "協助藥物跨膜；會飽和、會被競爭（levodopa 與胺基酸）。", ref: ["pk_L1", 6] },
    { en: "Vd (apparent volume of distribution)", zh: "表觀分布體積", def: "Vd＝A/C，分布廣度的指標，不是真實體積；決定負荷劑量。", ref: ["pk_L1", 6] },
    { en: "Plasma protein binding", zh: "血漿蛋白結合", def: "主要與白蛋白結合，可逆；≥95% 為高度結合。", ref: ["pk_L1", 7] },
    { en: "Phase I / Phase II metabolism", zh: "第一相／第二相代謝", def: "官能基化（敲打）／接合反應；與臨床試驗分期無關。", ref: ["pk_L1", 8] },
    { en: "Prodrug / Active metabolite", zh: "前驅藥／活性代謝物", def: "需代謝才有活性（clopidogrel、codeine）；代謝物也可能有毒性。", ref: ["pk_L1", 8] },
    { en: "CYP450", zh: "細胞色素 P450", def: "主要代謝酵素家族；CYP3A 占比最高，小腸與肝臟都有。", ref: ["pk_L1", 9] },
    { en: "PM / EM / UM", zh: "慢速／正常／超快速代謝者", def: "代謝基因多型性造成的表型差異。", ref: ["pk_L1", 9] },
    { en: "Clearance (CL)", zh: "清除率", def: "連結排除速率與血漿濃度的比例常數；CL＝Q·ER；決定維持劑量與 Css。", ref: ["pk_L1", 10] },
    { en: "Extraction ratio (ER)", zh: "萃取比", def: "藥物流經器官一次被移除的比例；ER＝(Ca−Cv)/Ca。", ref: ["pk_L1", 10] },
    { en: "GFR", zh: "腎絲球過濾率", def: "與游離藥物濃度相關；＜80 mL/min 要考慮腎功能對排泄的影響。", ref: ["pk_L1", 11] },
    { en: "Nonlinear PK", zh: "非線性（劑量依賴）藥動學", def: "酵素或轉運飽和，劑量與 AUC 不成比例。", ref: ["pk_L1", 12] },
    { en: "Bridging study", zh: "銜接性試驗", def: "把國外資料外推到本國族群時，評估種族差異的試驗。", ref: ["pk_L1", 15] },
    { en: "One-compartment model", zh: "一室模型", def: "假設瞬間分布、一階排除，全身當成一個室。", ref: ["pk_L2", 2] },
    { en: "First-order elimination", zh: "一階排除", def: "單位時間排除固定「比例」；半對數圖呈直線。", ref: ["pk_L2", 2] },
    { en: "Elimination rate constant (k)", zh: "排除速率常數", def: "k＝CL/Vd＝ke＋km＋k<sub>others</sub>。", ref: ["pk_L2", 3] },
    { en: "Half-life (t½)", zh: "半衰期", def: "濃度降一半的時間；t½＝0.693/k；決定到達穩定態的快慢。", ref: ["pk_L2", 3] },
    { en: "Steady state (Css)", zh: "穩定態", def: "給藥速率＝排除速率；Css＝R₀/CL；約 4–5 個 t½ 達到。", ref: ["pk_L2", 3] },
    { en: "Loading dose", zh: "負荷劑量", def: "一開始就達到目標濃度的劑量；由 Vd 決定。", ref: ["pk_L2", 5] },
    { en: "Salt factor (S)", zh: "鹽類係數", def: "製劑中實際活性成分的比例。", ref: ["pk_L2", 5] },
    { en: "Absolute / Relative bioavailability", zh: "絕對／相對生體可用率", def: "和 IV 比／兩個血管外劑型互比（BE 試驗）。", ref: ["pk_L2", 7] },
    { en: "Lag time", zh: "延遲時間", def: "給藥後濃度還沒開始上升的那一段。", ref: ["pk_L2", 7] },
    { en: "Flip-flop kinetics", zh: "翻轉動力學", def: "ka＜k 時，曲線末端斜率反映吸收而不是排除。", ref: ["pk_L2", 8] },
    { en: "Superposition principle", zh: "疊加原理", def: "多劑濃度＝各單劑濃度相加；需一階排除且 PK 不隨劑量改變。", ref: ["pk_L2", 8] },
    { en: "Accumulation factor (R)", zh: "蓄積因子", def: "R＝1/(1−e<sup>−kτ</sup>)；給藥間隔越短，蓄積越多。", ref: ["pk_L2", 9] },
    { en: "Two-compartment model", zh: "二室模型", def: "中央室＋組織室；濃度曲線呈 α 分布相與 β 排除相。", ref: ["pk_L2", 10] },
  ],
  map: {
    w: 1660, h: 560,
    intro: "上排是 ADME 四個過程，最右邊是它們共同塑造出的血中濃度曲線與模型。點方塊看意義。",
    nodes: [
      { id: "root", label: "藥物動力學 PK", x: 800, y: 40, k: "root", def: "血中濃度之所以隨時間變化，是 ADME 四個過程造成的；參數是藥物的履歷表。", ref: ["pk_L1", 2] },
      { id: "A", label: "A 吸收", x: 130, y: 130, k: "group", def: "藥物從給藥部位到測量部位的過程。", ref: ["pk_L1", 4] },
      { id: "dis", label: "崩散→溶離", x: 130, y: 230, def: "不溶離就不吸收；長效、腸溶、舌下劑型不可破壞。", ref: ["pk_L1", 3] },
      { id: "ge", label: "胃排空／食物", x: 130, y: 320, def: "高脂餐延緩吸收；腹瀉讓停留時間不足。", ref: ["pk_L1", 5] },
      { id: "fp", label: "首渡效應", x: 130, y: 410, def: "腸壁（CYP3A4）與肝臟先代謝一部分。", ref: ["pk_L1", 4] },
      { id: "F", label: "F＝Fgl·Fgw·Fh", x: 130, y: 500, def: "生體可用率；F 低 → 個體差異大。", ref: ["pk_L1", 8] },
      { id: "D", label: "D 分布", x: 400, y: 130, k: "group", def: "灌流、擴散、蛋白與組織結合。", ref: ["pk_L1", 7] },
      { id: "fu", label: "蛋白結合 fu", x: 320, y: 230, def: "只有游離藥物有作用；低白蛋白 → fu↑。", ref: ["pk_L1", 7] },
      { id: "free", label: "游離藥物才作用", x: 320, y: 320, def: "才能過 BBB、被代謝、被過濾、產生副作用。", ref: ["pk_L1", 3] },
      { id: "vd", label: "Vd＝A/C", x: 490, y: 230, def: "分布廣度指標；決定負荷劑量；Vd 大 → t½ 長。", ref: ["pk_L1", 6] },
      { id: "M", label: "M 代謝", x: 670, y: 130, k: "group", def: "肝臟為主，小腸也會代謝。", ref: ["pk_L1", 8] },
      { id: "cyp", label: "CYP450", x: 670, y: 230, def: "CYP3A＞2D6＞2C＞1A2＞2E1；葡萄柚汁抑制 CYP3A4。", ref: ["pk_L1", 9] },
      { id: "poly", label: "多型性 PM/EM/UM", x: 670, y: 320, def: "同劑量不同反應的來源之一。", ref: ["pk_L1", 9] },
      { id: "pro", label: "Prodrug／活性代謝物", x: 670, y: 410, w: 170, def: "clopidogrel、codeine 需代謝才有作用。", ref: ["pk_L1", 8] },
      { id: "E", label: "E 排泄", x: 940, y: 130, k: "group", def: "主要經腎從尿液排出。", ref: ["pk_L1", 11] },
      { id: "cl", label: "CL＝Q·ER", x: 860, y: 230, def: "清除率；決定維持劑量與 Css。", ref: ["pk_L1", 10] },
      { id: "nl", label: "非線性 PK", x: 860, y: 320, def: "酵素飽和 → 劑量與 AUC 不成比例。", ref: ["pk_L1", 12] },
      { id: "gfr", label: "GFR", x: 1020, y: 230, def: "＜80 mL/min 要考慮腎功能影響。", ref: ["pk_L1", 11] },
      { id: "curve", label: "血中濃度曲線", x: 1230, y: 130, k: "group", def: "ADME 共同作用的結果。", ref: ["pk_L1", 1] },
      { id: "par", label: "Cmax／Tmax／AUC", x: 1230, y: 230, def: "速率（Cmax、Tmax）與程度（AUC）。", ref: ["pk_L2", 6] },
      { id: "tw", label: "MEC～MTC", x: 1230, y: 320, def: "治療區間。", ref: ["pk_L1", 1] },
      { id: "tdm", label: "TDM", x: 1230, y: 410, def: "治療區間窄的藥要監測濃度。", ref: ["pk_L1", 1] },
      { id: "one", label: "一室模型", x: 1400, y: 230, def: "瞬間分布、一階排除。", ref: ["pk_L2", 2] },
      { id: "half", label: "t½＝0.693/k", x: 1400, y: 320, def: "k＝CL/Vd；t½ 決定多快到穩定態。", ref: ["pk_L2", 3] },
      { id: "ss", label: "穩定態 4–5 t½", x: 1400, y: 410, def: "Css＝R₀/CL。", ref: ["pk_L2", 4] },
      { id: "ld", label: "負荷劑量", x: 1400, y: 500, def: "LD＝Vd·Cp／(S·F)，不用等 4–5 個 t½。", ref: ["pk_L2", 5] },
      { id: "two", label: "二室模型", x: 1570, y: 230, def: "α 分布相＋β 排除相。", ref: ["pk_L2", 10] },
    ],
    edges: [
      ["root", "A"], ["root", "D"], ["root", "M"], ["root", "E"], ["root", "curve"],
      ["A", "dis"], ["dis", "ge"], ["ge", "fp"], ["fp", "F"],
      ["D", "fu"], ["fu", "free"], ["D", "vd"],
      ["M", "cyp"], ["cyp", "poly"], ["poly", "pro"],
      ["E", "cl"], ["cl", "nl", "飽和"], ["E", "gfr"],
      ["curve", "par"], ["par", "tw"], ["tw", "tdm"],
      ["curve", "one"], ["one", "half"], ["half", "ss"], ["ss", "ld", "等不及"], ["curve", "two"],
      ["E", "curve", "決定下降速度"],
    ],
  },
};
